### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by mortezabarati** [ysoheilifar/issabel-Send-Mail-when-CDR-00#2]
Hi 
Thank you for your amazing solution. 
I'd done everything according the Read me instruction. I can view the 900* calls in https://IP_Address/checkcdr00.php but nothing email!
can you please explain a bit more?
Best Regards

**Comment by ysoheilifar** [comment]
Hi 
I write and test this solution on many issabel projects
 however this is my telegram id contact to me for solve your problem
@yaser_so
